Controllers/PetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using NToastNotify;
using PetDemo.Data;
using PetDemo.Models;
using PetDemo.Repository;

namespace PetDemo.Controllers
{
    public class PetController : BaseController<Pet>
    {
        private IPetRepository _petRepo;
        private readonly IToastNotification _toastNotification;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly INotificationRepository _notificationRepo;

        public PetController(IPetRepository petRepository,IToastNotification toastNotification,
                                UserManager<ApplicationUser> userManager, INotificationRepository notificationRepo)
        {
            _petRepo = petRepository;
            _toastNotification = toastNotification;
            _userManager = userManager;
            _notificationRepo = notificationRepo;
        }
        public IActionResult Index(string search, int page =1)
        {
            if (!string.IsNullOrEmpty(search))
            {
                var foundPets = _petRepo.SearchPets(search);
                return View(foundPets);
            }
            var pets = _petRepo.GetAllPets();
            //return View(pets);

            //pagination
            var enumerable = pets;
            List<Pet> asList = enumerable.ToList();//convert IEnumerable to list


            var paginatedResult = PaginatedResult(asList, page, 1);
            return View(paginatedResult);
        } 

        public IActionResult MyPets()
        {
            var userId = _userManager.GetUserId(this.HttpContext.User);
            var pets = _petRepo.GetPetByUserId(userId);
            return View(pets);
        }
        public IActionResult Details(int id)
        {
            var pet = _petRepo.GetSinglePet(id);
            return View(pet);
        }

        public IActionResult AddNew()
        {
            ViewBag.IsEditMode = "false";
            return View();
        }
        [HttpPost]
        [Authorize]
        public IActionResult AddNew(Pet pet, string IsEditMode)
        {
            var userId = _userManager.GetUserId(this.HttpContext.User);
            pet.UserId = userId;
            if (!ModelState.IsValid)
            {
                ViewBag.IsEditMood = IsEditMode;
                return View(pet);
            }
            else
            {
                if (IsEditMode.Equals("false"))
                {
                    _petRepo.Create(pet);
                    _toastNotification.AddSuccessToastMessage("Your Pet Is Created Successfully");
                    //_clientNotification.AddSweetNotification("successfully", "Your Pet Is Created.", NotificationType.success);
                }
                else
                {
                    _petRepo.Edit(pet);
                    _toastNotification.AddSuccessToastMessage("Your Pet Is Eidited Successfully");
                }

                return RedirectToAction("Index");
            }
        }
        public IActionResult Delete(int Id)
        {
            var pet = _petRepo.GetSinglePet(Id);
            _petRepo.Delete(pet);
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Edit(int Id)
        {
            var loggedInUserId = _userManager.GetUserId(HttpContext.User);

            ViewBag.IsEditMode = "true";
            var pet = _petRepo.GetSinglePet(Id);

            if(pet.UserId != loggedInUserId)
            {
                return Content("You are not authorized for this action");
            }

            _petRepo.Delete(pet);       //for remove same name problem and it delete the pat if some try to eddit other pat
            _toastNotification.AddWarningToastMessage("It Will Change the Pet Information!");

            return View("AddNew",pet);
        }

        public IActionResult ToggleSelling(int id)
        {
            var pet = _petRepo.GetSinglePet(id);
            pet.IsSelling = !pet.IsSelling;
            _petRepo.Edit(pet);

            //Selling notification

            var username = _userManager.GetUserName(HttpContext.User);
            var status = "";
            if (pet.IsSelling)
                status = "Selling";
            else
                status = "Not Selling";
            var notificaton = new Notification
            {
                Text = $"The {username} is {status} their pet." 
            };

            _notificationRepo.Create(notificaton, pet.Id);

            return RedirectToAction(nameof(Details), new { id = id });      //new { id(Details action perametter have to same) = id }
        }

        public IActionResult VerifyName(string Name)
        {
            if(_petRepo.VerifyName(Name))
            {
                return Json($"This Name {Name} Is Already Exists. Please Try Another Name");
            }
            return Json(true);
        }

        public IActionResult AutoCompleteResult(string search)
        {
            return Json(_petRepo.SearchPets(search));
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PetDemo</title>
    <link href="~/lib/twitter-bootstrap/css/bootstrap.css" rel="stylesheet" />
    <link href="~/lib/bootswatch/united/bootstrap.css" rel="stylesheet" />
    <link href="~/lib/toastr.js/toastr.css" rel="stylesheet" />
    <link href="~/lib/bootstrap-sweetalert/sweetalert.css" rel="stylesheet" />
    <link href="~/lib/easy-autocomplete/easy-autocomplete.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    @await Component.InvokeAsync("NToastNotify")

    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Pet" asp-action="Index">PetDemo</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pet" asp-action="Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Pet Manager - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <!-- Latest compiled and minified CSS -->
    @*<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">*@

    <!-- jQuery library -->
    @*<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>*@

    <!-- Popper JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>

    <!-- Latest compiled JavaScript -->
    @*<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>*@

    <script src="https://kit.fontawesome.com/712cb7ccea.js" crossorigin="anonymous"></script>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/twitter-bootstrap/js/bootstrap.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    <script src="~/lib/toastr.js/toastr.min.js"></script>
    <script src="~/lib/bootstrap-sweetalert/sweetalert.js"></script>
    <script src="~/lib/easy-autocomplete/jquery.easy-autocomplete.js"></script>
    <script src="~/lib/aspnet-signalr/signalr.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/Notification.js"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_Pagination.cshtml
@{
    var recordsPerPage = Model;
    var totalRecords = ViewBag.TotalRecords == null ? 0 : ViewBag.TotalRecords;
    int numberOfButtons;
    if (totalRecords % recordsPerPage == 0)
    {
        numberOfButtons = totalRecords / recordsPerPage;
    }
    else
    {
        numberOfButtons = (totalRecords / recordsPerPage) + 1;
    }
}
<ul class="pagination">
    @if (ViewBag.CurrentPage > 1)
    {
        <li>
            <a asp-route-page=@(ViewBag.CurrentPage-1)>Prev</a>
        </li>
    }

    @for (int i = 0; i < numberOfButtons; i++)
    {
        @if (ViewBag.CurrentPage < numberOfButtons)
        {
            <li>
                <a asp-route-page="@(ViewBag.CurrentPage+i)">@(ViewBag.CurrentPage+i)</a>
            </li>
        }
    }
    @if (ViewBag.CurrentPage < numberOfButtons)
    {
        <li>
            <a asp-route-page=@(ViewBag.CurrentPage+1)>Next</a>
        </li>
    }
</ul>